platform :ios, '7.0'
pod 'PureLayout', '~> 2.0.6'
pod 'KVNProgress'
pod 'AFNetworking', '~> 2.5.4'
pod 'iCarousel'
pod 'DZNEmptyDataSet'
pod 'WMPageController'
pod 'ActionSheetPicker-3.0', '~> 2.0.1'
pod 'TGCameraViewController'
pod "SKTagView"
pod 'HexColors'
pod 'Reachability', '~> 3.2'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJRefresh', '~> 3.0.7'
pod 'FMDB', '~> 2.5'
pod 'MJPhotoBrowser', '~> 1.0.2'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDCycleScrollView','~> 1.6'
pod 'Appirater'
pod 'Masonry'